---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      environment: dev
  template:
    metadata:
      labels:
        app: api
        environment: dev
    spec:
      imagePullSecrets:
      - name: registryaccess
      containers:
      - name: api
        image: iad.ocir.io/gse00014267/api:dev
        ports:
        - containerPort: 5000

---
apiVersion: v1 
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: api